name: Bash CI 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "scripts/**"
  workflow_dispatch:

jobs:
  project-validation:
    name: Show basic information
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: skript ausführbar machen 
        run: chmod +x scripts/*.sh
      - name: Validierung wird ausgeführt
        run: bash scripts/02_validate_project.sh
