name:  cronjob-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Skripte ausführbar machen
        run: chmod +x scripts/*.sh tests/*.sh

      - name: info zum skript 
        run: bash scripts/01_show_info.sh

      - name: validierung des projektes
        run: bash scripts/02_validate_project.sh

      - name: analysiere alle logs 
        run: bash scripts/03_analyze_logs.sh        
